### ISSUE TITLE
Config.reporter

### ISSUE THREAD

**Issue by ag-izzy** [xFutte/futte-newspaper#18] opened 2022-08-10 08:31 UTC
**What is your question?**
İf i use /setjob 1 reporter 3 
Reporter options gone page is going blank.
where is the problem i cant resolve it.

``` 
shared / jobs
	['reporter'] = {
		label = 'Reporter',
		defaultDuty = true,
		offDutyPay = true,
		grades = {
            ['0'] = {
                name = 'Rep',
                payment = 6
            },
            ['1'] = {
                name = 'Rep II',
                payment = 12
            },
            ['2'] = {
                name = 'Editor',
                payment = 14
            },
            ['3'] = {
                name = 'GYY',
                payment = 20
            },
        },
	},
```
paper config * i configured it for my perspective btw.
```


	// Remember to align this with QBShared.Jobs
	reporter: [
		{
			grade: 0,
			canPublish: false,
			canEdit: false,
			canDelete: false,
		},
		{
			grade: 1,
			canPublish: true,
			canEdit: false,
			canDelete: false,
		},
		{
			grade: 2,
			canPublish: true,
			canEdit: true,
			canDelete: false,
		},
		{
			grade: 3,
			canPublish: true,
			canEdit: true,
			canDelete: true,
		},
	],
```

**Comment by xFutte** [comment] 2022-08-10 13:32
Does it work with `/setjob 1 reporter 2`?

**Comment by ag-izzy** [comment] 2022-08-10 16:32
even if the rank is higher than 0, they "canPublish: true, CanEdit: true CanDelete: false" section is valued according to the rank 0.
checked 3 times. if i change value of "can" state true reporter actions comes back. it can't read other ranks even if i set in shared/jobs. or something like that. im still researching what was wrong.

**Comment by xFutte** [comment] 2022-08-10 19:11
Hm, I'll take a look at it when I have time and see if I can reproduce it.

**Comment by ag-izzy** [comment] 2022-08-10 19:13
noted thank you for now.

**Comment by xFutte** [comment] 2022-08-12 16:48
@ag-izzy I looked into this, and it works perfectly fine for me. My shared.lua looks like this:

```lua
['reporter'] = {
		label = 'Reporter',
		defaultDuty = true,
		grades = {
            ['0'] = {
                name = 'Journalist',
                payment = 50
            },
			['1'] = {
                name = 'Journalist',
                payment = 50
            },
			['2'] = {
                name = 'Journalist',
                payment = 50
            },
			['3'] = {
                name = 'Journalist',
                payment = 50
            },
        },
},
```
and my config.js
```js
reporter: [
		{
			grade: 0,
			canPublish: false,
			canEdit: false,
			canDelete: false,
		},
		{
			grade: 1,
			canPublish: true,
			canEdit: true,
			canDelete: true,
		},
		{
			grade: 2,
			canPublish: true,
			canEdit: true,
			canDelete: false,
		},
		{
			grade: 3,
			canPublish: true,
			canEdit: true,
			canDelete: true,
		},
	],
```

I don't know if it could be the reason, but you need to restart your server after making changes to shared.lua for the code to go through after adding grades.

Let me know if it works.

**Comment by xFutte** [comment] 2022-08-14 20:27
Closing the issue since I can't reproduce the "bug". Feel free to reopen.

**Closed by xFutte** 2022-08-14 20:27 UTC
Labels: question
